inherit_gem:
  runger_style:
    - rulesets/default.yml # gem 'rubocop'
    - rulesets/performance.yml # gem 'rubocop-performance'
    - rulesets/rspec.yml # gem 'rubocop-rspec'

AllCops:
  Exclude:
    - lib/generators/runger_actions/action/templates/action.rb
    - vendor/**/*
